"""
04_classify.py
Milestone 2 - Inference Methods

Loads features.csv and trains seven classifiers (imported from classifiers/):
  1. Logistic Regression (L2)       - GLM baseline
  2. SVM (RBF kernel)               - robust non-linear classifier
  3. Naive Bayes (plain)            - Bayesian baseline
  4. Naive Bayes (PCA-decorrelated) - Bayesian, independence assumption fixed
  5. QDA                            - full covariance Bayesian
  6. LASSO Logistic Regression      - sparsity / automatic feature selection
  7. Gradient Boosting              - ensemble, best overall performer (~85%)

Two feature sets are compared:
  - Hand-crafted : 7 time-domain + 5 spectral features (12 total)
  - PCA          : 50 principal components from 02_extract_features.py

Saves classifier_results.pkl, then calls 03_visualize.py to generate all plots.
Outputs:
  results_summary.csv      - per-method accuracy/AUC table
  classifier_results.pkl   - serialised models + results for 03_visualize.py
  visualizations/08-15.png - generated by 03_visualize.py
"""

import os
import pickle
import subprocess
import sys
import warnings
import pandas as pd
from dotenv import load_dotenv
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, auc, roc_curve
from sklearn.model_selection import (GridSearchCV, StratifiedKFold,
                                     cross_val_score, train_test_split)
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

from classifiers import (train_gradient_boosting, train_lasso,
                         train_logistic_regression, train_naive_bayes,
                         train_svm)
from classifiers.naive_bayes import train_plain, train_qda as _train_qda

warnings.filterwarnings("ignore")
load_dotenv()

# Config
FEATURES_FILE = os.getenv("FEATURES_FILE", "features.csv")
VIZ_DIR       = "visualizations"
RANDOM_STATE  = 42
TEST_SIZE     = 0.2
TARGET_ACC    = 0.85

HANDCRAFTED_COLS = [
    "rms", "max_amplitude", "zero_crossing_rate",
    "kurtosis", "skewness", "std",
    "energy_0p1_1p0hz", "energy_1p0_5p0hz",
    "energy_5p0_10p0hz", "energy_10p0_20p0hz",
    "dominant_frequency",
]
PCA_COLS = [f"pc{i}" for i in range(1, 51)]


# Data helpers
def load_data(path):
    df = pd.read_csv(path)
    print(f"Loaded {len(df)} samples  "
          f"(EQ={(df['label']==1).sum()}, Noise={(df['label']==0).sum()})\n")
    hc_cols  = [c for c in HANDCRAFTED_COLS if c in df.columns]
    pca_cols = [c for c in PCA_COLS if c in df.columns]
    return df[hc_cols].values, df[pca_cols].values, df["label"].values, hc_cols


def split_and_scale(X, y):
    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )
    sc = StandardScaler()
    return sc.fit_transform(X_tr), sc.transform(X_te), y_tr, y_te


# Evaluation
def evaluate(model, X_te, y_te, name):
    y_pred = model.predict(X_te)
    acc    = accuracy_score(y_te, y_pred)
    y_prob = (model.predict_proba(X_te)[:, 1]
              if hasattr(model, "predict_proba")
              else model.decision_function(X_te))
    fpr, tpr, _ = roc_curve(y_te, y_prob)
    roc_auc     = auc(fpr, tpr)
    marker      = " *" if acc >= TARGET_ACC else ""
    print(f"  {name:35s}  acc={acc:.3f}  AUC={roc_auc:.3f}{marker}")
    return {"name": name, "acc": acc, "auc": roc_auc,
            "fpr": fpr, "tpr": tpr, "y_pred": y_pred}


# 10-fold cross-validation (fixed hyperparameters, proper pipeline)
def compute_cv_scores(X, y):
    print("\n[CV] Running 10-fold cross-validation ...")
    cv   = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)
    n_hc = X.shape[1]

    classifiers = {
        "Logistic Regression": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", LogisticRegression(C=1.0, max_iter=1000,
                                       random_state=RANDOM_STATE)),
        ]),
        "SVM (RBF)": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", SVC(kernel="rbf", C=100, gamma="scale",
                        random_state=RANDOM_STATE)),
        ]),
        "Naive Bayes (plain)": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", GaussianNB()),
        ]),
        "Naive Bayes (PCA)": Pipeline([
            ("sc",  StandardScaler()),
            ("pca", PCA(n_components=n_hc)),
            ("clf", GaussianNB()),
        ]),
        "QDA": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", QuadraticDiscriminantAnalysis(reg_param=0.1)),
        ]),
        "LASSO LR": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", LogisticRegression(penalty="l1", C=0.1,
                                       solver="liblinear", max_iter=1000,
                                       random_state=RANDOM_STATE)),
        ]),
        "Gradient Boosting": Pipeline([
            ("sc",  StandardScaler()),
            ("clf", GradientBoostingClassifier(n_estimators=300, max_depth=2,
                                               learning_rate=0.2, subsample=0.8,
                                               random_state=RANDOM_STATE)),
        ]),
    }

    cv_scores = {}
    for name, pipe in classifiers.items():
        scores = cross_val_score(pipe, X, y, cv=cv, scoring="accuracy")
        cv_scores[name] = scores
        print(f"  {name:35s}  {scores.mean():.3f} +/- {scores.std():.3f}")

    return cv_scores


# Summary
def print_summary(hc_results, pca_results):
    print("\n" + "=" * 68)
    print(f"{'Method':<35} {'HC Acc':>7} {'HC AUC':>7} {'PCA Acc':>8} {'PCA AUC':>8}")
    print("-" * 68)
    for hc, pc in zip(hc_results, pca_results):
        flag = " *" if hc["acc"] >= TARGET_ACC else ""
        print(f"{hc['name']:<35} {hc['acc']:>7.3f} {hc['auc']:>7.3f} "
              f"{pc['acc']:>8.3f} {pc['auc']:>8.3f}{flag}")
    print("=" * 68)
    print("  * meets 85% target")
    best = max(hc_results, key=lambda r: r["acc"])
    print(f"\nBest: {best['name']}  acc={best['acc']:.3f}  AUC={best['auc']:.3f}")

    pd.DataFrame([
        {"method": hc["name"],
         "hc_acc": round(hc["acc"], 4), "hc_auc": round(hc["auc"], 4),
         "pca_acc": round(pc["acc"], 4), "pca_auc": round(pc["auc"], 4)}
        for hc, pc in zip(hc_results, pca_results)
    ]).to_csv("results_summary.csv", index=False)
    print("[saved] results_summary.csv")


# Main
def main():
    os.makedirs(VIZ_DIR, exist_ok=True)

    if not os.path.exists(FEATURES_FILE):
        raise FileNotFoundError(
            f"{FEATURES_FILE} not found. Run 02_extract_features.py first."
        )

    X_hc, X_pca, y, hc_names = load_data(FEATURES_FILE)

    # Hand-crafted feature set
    print("=" * 55)
    print("HAND-CRAFTED FEATURES")
    print("=" * 55)
    X_hc_tr, X_hc_te, y_tr, y_te = split_and_scale(X_hc, y)

    print("[1/7] Logistic Regression (L2) ...")
    lr = train_logistic_regression(X_hc_tr, y_tr)

    print("[2/7] SVM (RBF) — grid search ...")
    svm = train_svm(X_hc_tr, y_tr)

    print("[3/7] Naive Bayes ...")
    nb_plain = train_plain(X_hc_tr, y_tr)
    nb_pca   = train_naive_bayes(X_hc_tr, y_tr)
    qda      = _train_qda(X_hc_tr, y_tr)

    print("[4/7] LASSO Logistic Regression ...")
    lasso, C_vals, lasso_accs, lasso_nz = train_lasso(X_hc_tr, y_tr, hc_names)

    print("[5/7] Gradient Boosting ...")
    gb = train_gradient_boosting(X_hc_tr, y_tr)

    print("\nTest set results  (* = meets 85% target):")
    hc_results = [
        evaluate(lr,       X_hc_te, y_te, "Logistic Regression (L2)"),
        evaluate(svm,      X_hc_te, y_te, "SVM (RBF)"),
        evaluate(nb_plain, X_hc_te, y_te, "Naive Bayes (plain)"),
        evaluate(nb_pca,   X_hc_te, y_te, "Naive Bayes (PCA-decorrelated)"),
        evaluate(lasso,    X_hc_te, y_te, "LASSO Logistic Regression"),
        evaluate(gb,       X_hc_te, y_te, "Gradient Boosting"),
    ]
    if qda is not None:
        hc_results.append(evaluate(qda, X_hc_te, y_te, "QDA"))

    # PCA feature set
    print("\n" + "=" * 55)
    print("PCA FEATURES")
    print("=" * 55)
    X_pca_tr, X_pca_te, y_tr_p, y_te_p = split_and_scale(X_pca, y)

    lr_p = LogisticRegression(C=1.0, max_iter=1000,
                               random_state=RANDOM_STATE).fit(X_pca_tr, y_tr_p)
    svm_p = GridSearchCV(
        SVC(kernel="rbf", probability=True, random_state=RANDOM_STATE),
        {"C": [0.1, 1, 10, 100], "gamma": ["scale", "auto"]},
        cv=5, scoring="accuracy", n_jobs=-1,
    ).fit(X_pca_tr, y_tr_p)
    nb_plain_p = GaussianNB().fit(X_pca_tr, y_tr_p)
    nb_pca_p   = train_naive_bayes(X_pca_tr, y_tr_p)
    lasso_p    = LogisticRegression(penalty="l1", C=0.1, solver="liblinear",
                                    max_iter=1000,
                                    random_state=RANDOM_STATE).fit(X_pca_tr, y_tr_p)
    gb_p = GradientBoostingClassifier(
        n_estimators=300, max_depth=2, learning_rate=0.2,
        subsample=0.8, random_state=RANDOM_STATE,
    ).fit(X_pca_tr, y_tr_p)
    qda_p = QuadraticDiscriminantAnalysis(reg_param=0.1).fit(X_pca_tr, y_tr_p)

    print("\nTest set results:")
    pca_results = [
        evaluate(lr_p,       X_pca_te, y_te_p, "Logistic Regression (L2)"),
        evaluate(svm_p,      X_pca_te, y_te_p, "SVM (RBF)"),
        evaluate(nb_plain_p, X_pca_te, y_te_p, "Naive Bayes (plain)"),
        evaluate(nb_pca_p,   X_pca_te, y_te_p, "Naive Bayes (PCA-decorrelated)"),
        evaluate(lasso_p,    X_pca_te, y_te_p, "LASSO Logistic Regression"),
        evaluate(gb_p,       X_pca_te, y_te_p, "Gradient Boosting"),
        evaluate(qda_p,      X_pca_te, y_te_p, "QDA"),
    ]

    print_summary(hc_results, pca_results)

    # 10-fold CV
    cv_scores = compute_cv_scores(X_hc, y)

    # Save results for 03_visualize.py
    results_pkl = "classifier_results.pkl"
    with open(results_pkl, "wb") as f:
        pickle.dump({
            "hc_results":  hc_results,
            "pca_results": pca_results,
            "cv_scores":   cv_scores,
            "y_te":        y_te,
            "lr_model":    lr,
            "lasso_model": lasso,
            "gb_model":    gb,
            "C_vals":      C_vals,
            "lasso_accs":  lasso_accs,
            "lasso_nz":    lasso_nz,
            "hc_names":    hc_names,
        }, f)
    print(f"\n[saved] {results_pkl}")

    # Delegate all plotting to 03_visualize.py
    print("\nGenerating plots via 03_visualize.py ...")
    subprocess.run([sys.executable, "03_visualize.py"], check=True)


if __name__ == "__main__":
    main()
